name: mvvm_architecture
description: Chat App Using Flutter And Firebase

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0

  #state management
  stacked: ^1.2.2

  #navigation
  auto_route:  ^0.6.9
  stacked_services: ^0.6.0

  #cached_network_image
  cached_network_image: ^2.5.0

  #icons
  flutter_icons: ^1.1.0

  #equatable
  equatable: ^1.2.5

  #dependency injection
  get_it: ^5.0.4
  injectable: ^1.0.7

  #firebase
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0
  firebase_auth: ^0.20.0
  firebase_storage: ^7.0.0

  #google_sign_in
  google_sign_in: ^4.5.9


  #intl
  intl: ^0.16.1






dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  auto_route_generator: ^0.6.9
  injectable_generator:

flutter:

  uses-material-design: true
  assets:
    - assets/images/

